[project]
name = "thoa"
version = "0.1.0"
description = "Thoa Command Line Interface for Remote Job Submission"
authors = [
    {name = "GWC GmbH",email = "hello@gwc-solutions.ch"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "typer (>=0.16.0,<0.17.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "typing-extensions (>=4.14.1,<5.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "azure-storage-blob (>=12.26.0,<13.0.0)",
    "websockets (>=15.0.1,<16.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
thoa = "thoa.entrypoint:main"
